# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: boringhex.top博客
subtitle: '非典型程序员的小破站'
description: '分享电子、嵌入式和计算机技术'
keywords: 开发, 设计, 计算机, 电子, 信息, 嵌入式, 系统, 技术, 软件, 硬件, 物联网, MCU, PCB, 单片机, 电路, 编程
author: boringhex.top
language: zh-CN
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://blog.boringhex.top
permalink: posts/:hash/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:
tag_generator:
  enable_index_page: false


# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

## Plugin: hexo-generator-feed
feed:
  enable: true  # Enables or disables this plugin. Enabled by default.
  # type: atom  # Feed type. atom or rss2. Specify ['atom', 'rss2'] to output both types. (Default: atom)
  # path: atom.xml # Feed path. When both types are specified, path must follow the order of type value. (Default: atom.xml/rss2.xml)
  # limit: 20 # Maximum number of posts in the feed (Use 0 or false to show all posts)
  # hub:  # URL of the PubSubHubbub hubs (Leave it empty if you don't use it)
  # content: true # (optional) set to 'true' to include the contents of the entire post in the feed.
  # content_limit: 140  # (optional) Default length of post content used in summary. Only used, if content setting is false and no custom post description present.
  # content_limit_delim: ' '  # (optional) If content_limit is used to shorten post contents, only cut at the last occurrence of this delimiter before reaching the character limit. Not used by default.
  # order_by: -date # Feed order-by. (Default: -date)
  # icon: icon.png  # (optional) Custom feed icon. Defaults to a gravatar of email specified in the main config.
  # autodiscovery: true # Add feed autodiscovery. (Default: true)
  # template: # Custom template path(s). This file will be used to generate feed xml file, see the default templates: atom.xml and rss2.xml.

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''
